### ISSUE TITLE
CollapsibleTableViewHeader.swift #selector

### ISSUE THREAD

**Issue by pablomtz23** [jeantimex/CollapsibleTableSectionViewController#57]
CollapsibleTableViewHeader.swift:52:75: Argument of '#selector' refers to instance method 'tapHeader' that is not exposed to Objective-C

**Comment by galblank** [comment]
@objc func tapHeader(_ gestureRecognizer: UITapGestureRecognizer)
this is what needs to be done in order for this to work.
I've manually changed that inside CollapsibleTableViewHeader

**Comment by jbarros35** [comment]
don't close it its not closed.

Argument of '#selector' refers to instance method 'tapHeader' that is not exposed to Objective-C
at line 54. CollapsibleTableViewHeader
Xcode 10.1
